

	
	<nav class="navbar  nav bg-info">

  <li class="nav">
    <a class="nav-link link-active link-dark"  href="<?php echo $this->getUrl('admin','grid'); ?>">
     <i>ADMIN</i></a>
  </li>
  <li class="nav">
    <a class="nav-link active link-dark"  href="<?php echo $this->getUrl('product','grid'); ?>">
    <i>PRODUCT</i></a>
  </li>
 <li class="nav">
    <a class="nav-link active link-dark"  href="<?php echo $this->getUrl('category','grid'); ?>">
    <i>CATEGORY</i></a>
  </li>
  <li class="nav">
    <a class="nav-link active link-dark "   href="<?php echo $this->getUrl('customer','grid'); ?>">
    <i>CUSTOMER</i></a>
  </li>
   <li class="nav">
    <a class="nav-link active link-dark"  href="<?php echo $this->getUrl('vendor','grid'); ?>">
    <i>VENDOR</i></a>
  </li>
  <li class="nav">
    <a class="nav-link active link-dark"  href="<?php echo $this->getUrl('salesman','grid'); ?>">
    <i>SALESMAN</i></a>
  </li>
  <li class="nav">
    <a class="nav-link active link-dark"  href="<?php echo $this->getUrl('shipping','grid'); ?>">
    <i>SHIPPING METHOD</i></a>
  </li>
  <li class="nav">
    <a class="nav-link active link-dark"  href="<?php echo $this->getUrl('payment','grid'); ?>">
   <i> PAYMENT METHOD</i></a>
  </li>
  <li class="nav">
    <a class="nav-link active link-dark"  href="<?php echo $this->getUrl('eav_attribute','grid'); ?>"><i>EAV_ATTRIBUTE</i></a>
  </li>


