 <?php
$result = $this->admin;
?> 

	<form action="<?php echo $this->getUrl('admin','save');?>" method="POST">
		<table width="20%">
			<tr>
				<td><h3> ADMIN </h3></td>
				<td><button class="btn btn-primary">SAVE</button></td>
			</tr>
		</table>
		<table>
			 
			<tr>
				<td>adminId :</td>
				<td><input type="number" name="admin[admin_id]"
				 value="<?php echo $result->admin_id;?>"></td>
			</tr>
			<tr>
				<td>Email :</td>
				<td><input type="text" name="admin[email]" value="<?php echo $result->email;?>"></td>
			</tr>
			<tr>
					<td> Status</td>
					<td> <select name="admin[status]" >
						<?php foreach ($result->getResource()->getStatusOptions() as $key => $value): ?>
						<option value="<?php echo $key ?>"><?php echo $value ?></option>
						<?php endforeach; ?>
						
					</select> </td>
				</tr>
			
			 
		</table>
	</form>

</body>
</html>