<?php
$data = $this->getAdmins();
	?>

	<div class="row">
		<div class="col-9">
			<h3>Admin</h3>
		</div>
		<div class="col-3">
			<div class="btn btn-info link-secondary"><a href="<?php echo $this->getUrl('admin','add'); ?>">Add Admin</a></div>
	</div>

	<table class="table table-hover table-bordered flx ">
			<thead class="thead-light">
		<tr class="table-success">
			<th>AdminId</th>		
			<th>email</th>		
			<th>status</th>		
			<th>Created At</th>	
			<th>Updated At</th>	
			<th>Edit</th>	
			<th>Delete</th>	
		</tr>
	</thead>

		<?php foreach ($data->getData() as $row):  ?>
			<tr>
				<td><?php echo $row->admin_id;?></td>
				<td><?php echo $row->email;?></td>
				<td><?php echo $row->getstatustext();?></td>
				<td><?php echo $row->create_at;?></td>
				<td><?php echo $row->update_at;?></td>
				<td><a href="<?php echo $this->getUrl('admin','edit',
				['admin_id'=>$row->admin_id]);?>">Edit</a></td>
				<td><a href="<?php echo $this->getUrl('admin','delete',
				['admin_id'=>$row->admin_id]);?>">Delete</a></td>
				
			</tr>
			<?php endforeach; ?>	
	</table>

